map("n", "ga", "<Cmd>lua require('harpoon.mark').add_file()<cr>")
map("n", "g1", "<Cmd>lua require('harpoon.mark').set_current_at(1)<cr>")
map("n", "g2", "<Cmd>lua require('harpoon.mark').set_current_at(2)<cr>")
map("n", "g3", "<Cmd>lua require('harpoon.mark').set_current_at(3)<cr>")
map("n", "g4", "<Cmd>lua require('harpoon.mark').set_current_at(4)<cr>")
map("n", "<leader>rr", "<Cmd>lua require('harpoon.mark').rm_file()<cr>")

map("n", "<leader>m", "<Cmd>lua require('harpoon.ui').toggle_quick_menu()<cr>")
map("n", "<leader>1", "<Cmd>lua require('harpoon.ui').nav_file(1)<cr>")
map("n", "<leader>2", "<Cmd>lua require('harpoon.ui').nav_file(2)<cr>")
map("n", "<leader>3", "<Cmd>lua require('harpoon.ui').nav_file(3)<cr>")
map("n", "<leader>4", "<Cmd>lua require('harpoon.ui').nav_file(4)<cr>")
